import { Createstage } from "./gameHelper";
let stage = [
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
  [
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
    [0, "clear"],
  ],
];
test("Test CreateStage", () => expect(Createstage()).toStrictEqual(stage));
